### ISSUE TITLE
"composer update" on sf 2.3.9 project to 2.3.39 throws error in user bundle

### ISSUE THREAD

**Issue by dalu** [FriendsOfSymfony/FOSUserBundle#2109]
```
composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
  - Removing symfony/icu (v1.2.0)
  - Removing twig/twig (v1.15.0)
  - Installing twig/twig (v1.24.0)
    Downloading: 100%         

  - Removing doctrine/lexer (v1.0)
  - Installing doctrine/lexer (v1.0.1)
    Downloading: 100%         

  - Removing doctrine/inflector (v1.0)
  - Installing doctrine/inflector (v1.1.0)
    Downloading: 100%         

  - Removing doctrine/collections (v1.1)
  - Installing doctrine/collections (v1.3.0)
    Downloading: 100%         

  - Removing doctrine/cache (v1.3.0)
  - Installing doctrine/cache (v1.6.0)
    Downloading: 100%         

  - Removing doctrine/annotations (v1.1.2)
  - Installing doctrine/annotations (v1.2.7)
    Downloading: 100%         

  - Removing doctrine/common (v2.4.1)
  - Installing doctrine/common (v2.4.3)
    Downloading: 100%         

  - Installing symfony/polyfill-mbstring (v1.1.1)
    Downloading: 100%         

  - Installing symfony/polyfill-apcu (v1.1.1)
    Downloading: 100%         

  - Installing paragonie/random_compat (v1.4.1)
    Downloading: 100%         

  - Removing symfony/symfony (v2.3.9)
  - Installing symfony/symfony (v2.3.39)
    Downloading: 100%         

  - Removing doctrine/dbal (2.3.4)
  - Installing doctrine/dbal (2.3.5)
    Downloading: 100%         

  - Removing doctrine/orm (2.3.4)
  - Installing doctrine/orm (v2.3.6)
    Downloading: 100%         

  - Removing kriswallsmith/assetic (v1.1.2)
  - Installing kriswallsmith/assetic (v1.1.3)
    Downloading: 100%         

  - Removing symfony/assetic-bundle (v2.3.0)
  - Installing symfony/assetic-bundle (v2.3.1)
    Downloading: 100%         

  - Removing swiftmailer/swiftmailer (v5.0.3)
  - Installing swiftmailer/swiftmailer (v5.4.1)
    Downloading: 100%         

  - Removing symfony/swiftmailer-bundle (v2.3.4)
  - Installing symfony/swiftmailer-bundle (v2.3.11)
    Downloading: 100%         

  - Removing sensio/distribution-bundle (v2.3.4)
  - Installing sensio/distribution-bundle (v2.3.22)
    Downloading: 100%         

  - Removing sensio/generator-bundle (v2.3.4)
  - Installing sensio/generator-bundle (v2.3.5)
    Downloading: 100%         

  - Removing incenteev/composer-parameter-handler (v2.1.0)
  - Installing incenteev/composer-parameter-handler (v2.1.2)
    Downloading: 100%         

  - Installing behat/transliterator (v1.1.0)
    Downloading: 100%         

  - Removing gedmo/doctrine-extensions (v2.3.8)
  - Installing gedmo/doctrine-extensions (v2.4.13)
    Downloading: 100%         

  - Removing stof/doctrine-extensions-bundle (dev-master)
  - Installing stof/doctrine-extensions-bundle (dev-master 4e7499d)
    Cloning 4e7499d25dc5d0862da09fa8e336164948a29a25

  - Removing salavert/time-ago-in-words (v1.0)
  - Installing salavert/time-ago-in-words (v1.6.2)
    Downloading: 100%         

  - Removing jdorn/sql-formatter (v1.2.16)
  - Installing jdorn/sql-formatter (v1.2.17)
    Downloading: 100%         

  - Removing monolog/monolog (1.7.0)
  - Installing monolog/monolog (1.18.2)
    Downloading: 100%         

  - Removing jms/cg (1.0.0)
  - Installing jms/cg (1.1.0)
    Downloading: 100%         

  - Removing jms/metadata (1.5.0)
  - Installing jms/metadata (1.5.1)
    Downloading: 100%         

  - Removing jms/aop-bundle (1.0.1)
  - Installing jms/aop-bundle (1.2.0)
    Downloading: 100%         

  - Removing jms/di-extra-bundle (1.4.0)
  - Installing jms/di-extra-bundle (1.7.0)
    Downloading: 100%         

  - Removing doctrine/data-fixtures (v1.0.0)
  - Installing doctrine/data-fixtures (v1.0.2)
    Downloading: 100%         

  - Removing phpoption/phpoption (1.3.0)
  - Installing phpoption/phpoption (1.5.0)
    Downloading: 100%         

  - Removing friendsofsymfony/user-bundle (dev-master)
  - Installing friendsofsymfony/user-bundle (dev-master 16b04c4)
    Cloning 16b04c49af05dd3fb381e4abe04f0e5e231ac76d

  - Removing jms/security-extra-bundle (dev-master)
  - Installing jms/security-extra-bundle (dev-master c0147c2)
    Cloning c0147c282f345eee1424a4a42817662f4d4e3875

  - Removing doctrine/doctrine-fixtures-bundle (dev-master)
  - Installing doctrine/doctrine-fixtures-bundle (dev-master 0f1a2f9)
    Cloning 0f1a2f91b349e10f5c343f75ab71d23aace5b029

paragonie/random_compat suggests installing ext-libsodium (Provides a modern crypto API that can be used to generate random bytes.)
Writing lock file
Generating autoload files
> Incenteev\ParameterHandler\ScriptHandler::buildParameters
Updating the "app/config/parameters.yml" file
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::buildBootstrap
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache
Clearing the cache for the dev environment with debug true
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installAssets
Installing assets using the hard copy option
Installing assets for Symfony\Bundle\FrameworkBundle into web/bundles/framework
Installing assets for Dalu\ArchgamesBundle into web/bundles/daluarchgames
Installing assets for Sensio\Bundle\DistributionBundle into web/bundles/sensiodistribution
> Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::installRequirementsFile
```

This was the update

when trying to log in following output:

```
exception &#039;Symfony\Component\Security\Core\Exception\AuthenticationServiceException&#039; with message &#039;Unrecognized field: usernameCanonical&#039; in /var/customers/webs/dluketic/archivedgames.com/vendor/symfony/symfony/src/Symfony/Component/Security/Core/Authentication/Provider/DaoAuthenticationProvider.php:94
Stack trace:
#0 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(105): session_start()
#1 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(180): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage-&gt;start()
#2 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(480): Symfony\Component\HttpFoundation\Session\Storage\NativeSessionStorage-&gt;getBag(&#039;attributes&#039;)
#3 /var/customers/webs/dluketic/archivedgames.com/vendor/symfony/symfony/src/Symfony/Component/Security/Http/Firewall/ContextListener.php(77): Symfony\Component\HttpFoundation\Session\Session-&gt;get(&#039;_security_main&#039;)
#4 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(2372): Symfony\Component\Security\Http\Firewall\ContextListener-&gt;handle(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#5 [internal function]: Symfony\Component\Security\Http\Firewall-&gt;onKernelRequest(Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#6 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(1686): call_user_func(Array, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#7 /var/customers/webs/dluketic/archivedgames.com/app/cache/prod/classes.php(1615): Symfony\Component\EventDispatcher\EventDispatcher-&gt;doDispatch(Array, &#039;kernel.request&#039;, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#8 /var/customers/webs/dluketic/archivedgames.com/app/bootstrap.php.cache(2958): Symfony\Component\EventDispatcher\EventDispatcher-&gt;dispatch(&#039;kernel.request&#039;, Object(Symfony\Component\HttpKernel\Event\GetResponseEvent))
#9 /var/customers/webs/dluketic/archivedgames.com/app/bootstrap.php.cache(2943): Symfony\Component\HttpKernel\HttpKernel-&gt;handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1)
#10 /var/customers/webs/dluketic/archivedgames.com/app/bootstrap.php.cache(3072): Symfony\Component\HttpKernel\HttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#11 /var/customers/webs/dluketic/archivedgames.com/app/bootstrap.php.cache(2343): Symfony\Component\HttpKernel\DependencyInjection\ContainerAwareHttpKernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request), 1, true)
#12 /var/customers/webs/dluketic/archivedgames.com/web/app.php(24): Symfony\Component\HttpKernel\Kernel-&gt;handle(Object(Symfony\Component\HttpFoundation\Request))
#13 {main}
```

```php
<?php
namespace Dalu\UserBundle\Entity;

use FOS\UserBundle\Model\User as BaseUser;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="User")
 */
class User extends BaseUser
{
    /**
     * @ORM\Id
     * @ORM\Column(type="integer")
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    protected $id;

    public function __construct()
    {
        parent::__construct();
        // your own logic
    }

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }
}
```

```
app/console doctrine:schema:update --dump-sql
DROP INDEX UNIQ_2DA1797792FC23A8 ON User;
DROP INDEX UNIQ_2DA17977A0D96FBF ON User;
ALTER TABLE User DROP username, DROP username_canonical, DROP email, DROP email_canonical, DROP enabled, DROP salt, DROP password, DROP last_login, DROP locked, DROP expired, DROP expires_at, DROP confirmation_token, DROP password_requested_at, DROP roles, DROP credentials_expired, DROP credentials_expire_at
```

```
$ composer info
behat/transliterator                 v1.1.0             String transliterator
doctrine/annotations                 v1.2.7             Docblock Annotations Parser
doctrine/cache                       v1.6.0             Caching library offering an object-oriented API for many cache backends
doctrine/collections                 v1.3.0             Collections Abstraction library
doctrine/common                      v2.4.3             Common Library for Doctrine projects
doctrine/data-fixtures               v1.0.2             Data Fixtures for all Doctrine Object Managers
doctrine/dbal                        2.3.5              Database Abstraction Layer
doctrine/doctrine-bundle             v1.2.0             Symfony DoctrineBundle
doctrine/doctrine-fixtures-bundle    dev-master 0f1a2f9 Symfony DoctrineFixturesBundle
doctrine/inflector                   v1.1.0             Common String Manipulations with regard to casing and singular/plural rules.
doctrine/lexer                       v1.0.1             Base library for a lexer that can be used in Top-Down, Recursive Descent Parsers.
doctrine/orm                         v2.3.6             Object-Relational-Mapper for PHP
friendsofsymfony/user-bundle         dev-master 16b04c4 Symfony FOSUserBundle
gedmo/doctrine-extensions            v2.4.13            Doctrine2 behavioral extensions
incenteev/composer-parameter-handler v2.1.2             Composer script handling your ignored parameter file
jdorn/sql-formatter                  v1.2.17            a PHP SQL highlighting library
jms/aop-bundle                       1.2.0              Adds AOP capabilities to Symfony2
jms/cg                               1.1.0              Toolset for generating PHP code
jms/di-extra-bundle                  1.7.0              Allows to configure dependency injection using annotations
jms/metadata                         1.5.1              Class/method/property metadata management in PHP
jms/parser-lib                       1.0.0              A library for easily creating recursive-descent parsers.
jms/security-extra-bundle            dev-master c0147c2 Enhances the Symfony2 Security Component by adding several new features
kriswallsmith/assetic                v1.1.3             Asset Management for PHP
monolog/monolog                      1.18.2             Sends your logs to files, sockets, inboxes, databases and various web services
paragonie/random_compat              v1.4.1             PHP 5.x polyfill for random_bytes() and random_int() from PHP 7
phpoption/phpoption                  1.5.0              Option Type for PHP
psr/log                              1.0.0              Common interface for logging libraries
salavert/time-ago-in-words           v1.6.2             Time ago Twig extension where you can easily convert a datetime or timestamp to a distance of time in words.
sensio/distribution-bundle           v2.3.22            The base bundle for the Symfony Distributions
sensio/framework-extra-bundle        v2.3.4             This bundle provides a way to configure your controllers with annotations
sensio/generator-bundle              v2.3.5             This bundle generates code for you
stof/doctrine-extensions-bundle      dev-master 4e7499d Integration of the gedmo/doctrine-extensions with Symfony2
swiftmailer/swiftmailer              v5.4.1             Swiftmailer, free feature-rich PHP mailer
symfony/assetic-bundle               v2.3.1             Integrates Assetic into Symfony2
symfony/monolog-bundle               v2.3.0             Symfony MonologBundle
symfony/polyfill-apcu                v1.1.1             Symfony polyfill backporting apcu_* functions to lower PHP versions
symfony/polyfill-mbstring            v1.1.1             Symfony polyfill for the Mbstring extension
symfony/swiftmailer-bundle           v2.3.11            Symfony SwiftmailerBundle
symfony/symfony                      v2.3.39            The Symfony PHP framework
twig/extensions                      v1.0.1             Common additional features for Twig that do not directly belong in core
twig/twig                            v1.24.0            Twig, the flexible, fast, and secure template language for PHP
```

Where might the problem be?

**Comment by dalu** [comment]
```
$ php -v
PHP 5.5.33-1~dotdeb+7.1 (cli) (built: Mar  3 2016 17:11:35) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
```

**Comment by dalu** [comment]
"fixed" with
```
"friendsofsymfony/user-bundle": "dev-master#e770bfa2fd0fc665f55cd7cfeb34bddeffb892f4",
```

a39d000577d735444bee97de9f5ee382e3f85fa1 aka "remove legacy code" broke 2.3 support

**Comment by xabbuh** [comment]
@dalu Updating DoctrineBundle to 1.3 or higher should solve your issue (the compiler pass for registering entity mapping was introduced in 1.3.0).
